### ISSUE TITLE
Investigate reduced SVG dependency

### ISSUE THREAD

**Issue by sglanzer** [ciena-frost/ember-frost-viz#1]
SVG is great because it's reasonably fast, usually can be styled using CSS, and slots nicely into the DOM.

There are definitely special cases where a Canvas-based drawing API would be better in some areas.

Right now you can't just replace an SVG potter with a canvas plotter. The issues are:

1) tagNames should be computed. Right now they're all hardcoded SVG tag names.
2) Box mixin: scale components and plotters are sized by rendering once, then asking the DOM for dimensions

This could be improved with some effort, if it's worthwhile.

**Comment by notmessenger** [comment]
This add-on is deprecated so will not address.
