### ISSUE TITLE
Can't label axes

### ISSUE THREAD

**Issue by justinbowes** [ciena-frost/ember-frost-viz#28]
@srowhani wanted to add an axis label, which sounds reasonable, right?

The scale component is purely concerned with ticks and labels. There should be a wrapping component called an Axis.

## Component proposal

Usage:

Replace
```hbs
{{frost-viz/scale transform dataBindings.y.[0] align="left" ticks=10 tickLabelFormat=(frost-viz/format/numeric)}}
```

with
```hbs
{{frost-viz/axis transform label="Altitude" align="left" as |axis|}}
    {{frost-viz/scale axis dataBindings.y.[0] ticks=10 tickLabelFormat=(frost-viz/format/numeric)}}
{{/frost-viz/axis}}
```
wherever you need axis labels, which is, like, everywhere.        

Rough sketch:

### Component composition
* mixes in SVGAffineTransformable, so it's positionable by its parent like a Scale is
* mixes in DOMBox, so it can be styled with CSS
* mixes in Area, so it has a child area
* mixes in ScopeProvider, so it can yield a scope

### API
* accepts scope as positional parameter
* accepts align as parameter
* accepts label text as parameter
* accepts component name of label renderer, defaulting to a simple svg text renderer
* accepts scale component as block

### Implementation
* has computed property, labelElement
* computes label position based on align and padding 
   * e.g. align=left: label rect is ((area.left, area.top) to (innerArea.left, area.bottom))

### Template
* template renders the label using {{ component labelComponentRenderer }}
* template yields to scope component

----

#### edits
* Cleaned up sample formatting
* Added "align" to axis in the sample, and removed it from the scale...we can pass it on the yield (does that work? can you `yield positional named=val` and have that merge with parameters passed in the outer template?) or, failing that, add it to the scope and alias it in the Scale component

**Comment by sglanzer** [comment]
We'll either be building this shortly or hacking around it temporarily - either way it's on the short list for the next pass at this addon

**Comment by notmessenger** [comment]
This add-on is deprecated so will not address.
